module.exports = {
  C: [
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
  ],
  'C#/Db': [
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
  ],
  D: [
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
  ],
  'D#/Eb': [
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
  ],
  E: [
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'}
  ],
  F: [
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'}
  ],
  'F#/Gb': [
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
  ],
  G: [
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
  ],
  'G#/Ab': [
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
  ],
  A: [
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'}
  ],
  'A#/Bb': [
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
  ],
  B: [
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
  ],
}