module.exports = {
  B1: [
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
  ],
  E2: [
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'}
  ],
  A2: [
    {note: 'A', displayType: 'neutral'},
    {note: 'Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'}
  ],
  D3: [
    {note: 'D', displayType: 'neutral'},
    {note: 'Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'}
  ],
  G3: [
    {note: 'G', displayType: 'neutral'},
    {note: 'Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
  ],
  B3: [
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
  ],
  E4: [
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'}
  ],
}