module.exports = {
  B1: [
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
  ],
  E2: [
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'}
  ],
  A2: [
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'}
  ],
  D3: [
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'}
  ],
  G3: [
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
  ],
  B3: [
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
  ],
  E4: [
    {note: 'E', displayType: 'neutral'},
    {note: 'F', displayType: 'neutral'},
    {note: 'F#/Gb', displayType: 'neutral'},
    {note: 'G', displayType: 'neutral'},
    {note: 'G#/Ab', displayType: 'neutral'},
    {note: 'A', displayType: 'neutral'},
    {note: 'A#/Bb', displayType: 'neutral'},
    {note: 'B', displayType: 'neutral'},
    {note: 'C', displayType: 'neutral'},
    {note: 'C#/Db', displayType: 'neutral'},
    {note: 'D', displayType: 'neutral'},
    {note: 'D#/Eb', displayType: 'neutral'},
    {note: 'E', displayType: 'neutral'}
  ],
}